# Generated by Django 4.1.2 on 2022-10-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.IntegerField(db_index=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("json", models.JSONField()),
                (
                    "types",
                    models.ManyToManyField(related_name="pokemons", to="pokedex.type"),
                ),
            ],
        ),
    ]
